Feat/nft avatar migration
namehash/namekit pull request #301
Opened 2024-07-08 03:08 UTC by FrancoAguzzi

2024-07-09 20:13 UTC, lightwalker-eth requested changes
@FrancoAguzzi Wow this is a really big PR with lots of progress. Excited to see this.

There's a few key follow ups that need your help:
1. I wasn't able to test any of this because preview deployments are failing. Please investigate and resolve.
2. There's several places where I saw an issue that I remember previously sharing a code review feedback on, but now that feedback is gone from this PR 301. It seems there's some other earlier PR where I had open feedback for you but that isn't reflected in PR 301 yet? Can you please investigate? I'm worried that I saw some important issue in a different PR and added comments for it there but those ideas are not being reflected in PR 301.
3. There's a few files inside nameguard-react that I think should be removed as they now  should exclusively live inside namekit-react. Right?
4. Added other comments and feedback for you :+1:

2024-07-09 20:13 UTC, lightwalker-eth commented on apps/storybook/stories/Namekit/RegistrationPriceInfo.stories.tsx
> +const ELEVEN_DAYS_FROM_NOW_TIMESTAMP = buildTimestamp(
I remember leaving a comment about this in another PR. Can you please look for where those comments were and follow up on all of those again in this PR?

I'm worried that some of the detailed comments and feedback I've shared somewhere else is getting lost.

2024-07-12 00:30 UTC, FrancoAguzzi commented on packages/nameguard-react/src/components/TruncatedText/TruncatedText.tsx
I've added documentation to come back to this removal once things are stable, after the new comp. is merged into main, as agreed :)

2024-07-12 09:35 UTC, lightwalker-eth reviewed
@FrancoAguzzi Thanks for updates. Reviewed and shared feedback.

2024-07-12 09:35 UTC, lightwalker-eth commented on packages/namekit-react/src/components/EnsAvatar.tsx
> +        normalization={name.normalization as Normalization}
Hmm. Why wouldn't the type system already know that `name.normalization` is type `Normalization`?

2024-08-16 06:39 UTC, closed without merging