feat: [sc-25504] Proposed "maturity" next steps for NameGuard JS
namehash/namekit pull request #347
Opened 2024-08-07 11:12 UTC by Carbon225

Story details: https://app.shortcut.com/ps-web3/story/25504

2024-09-05 19:43 UTC, lightwalker-eth requested changes
@Carbon225 Hey really nice to see these updates :+1: Reviewed and shared feedback. Could you please also add a changeset to this PR? We need a changeset on this PR for both NameGuard SDK and NameGuard JS.

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-js/src/impersonation.test.ts
>  describe("Impersonation", () => {
```suggestion
describe("computeImpersonationEstimate", () => {
```

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBe("unlikely");
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBeNull();
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBeNull();
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBeNull();
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBeNull();
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBeNull();
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBe("unlikely");
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBe("potential");
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
> +    expect(data.impersonation_estimate).toBe("unlikely");
I see a "Check failure" on this line inside GitHub's PR review interface. Could you please investigate? Thanks

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-sdk/src/index.test.ts
>  describe("NameGuard", () => {
Suggest making a separate `describe(...` for each function we unit test and then make that function name the string passed to `describe(...`.

2024-09-05 19:43 UTC, lightwalker-eth commented on packages/nameguard-js/src/secureprimaryName.test.ts
> +const TEST_TIMEOUT = 30000;
```suggestion
const TEST_TIMEOUT_MS = 30000;
```

Is it correct to assume these are measured in milliseconds? Suggesting this change to make the unit of measurement more explicit.

2024-09-16 22:28 UTC, Carbon225 commented
@lightwalker-eth the tests are failing because they are using the production API deployment (should that be the case @djstrong?)

I have all tests passing when running this PR's API locally:
<img width="896" alt="image" src="https://github.com/user-attachments/assets/190782f9-ade6-4e23-9d8e-5758f12a6e33">
<img width="896" alt="image" src="https://github.com/user-attachments/assets/fe25bc40-b82c-4e9e-98b6-b0b0e6922d98">

I've implemented all other review suggestions.

2024-09-25 13:18 UTC, lightwalker-eth reviewed
Latest changes look good :+1: Review still in progress.

2024-10-20 14:56 UTC, Carbon225 commented
@djstrong all done. Typescript nameguard-sdk tests are failing because of the _status -> _estimate rename (not yet deployed). SDK tests pass on my machine when I set `NAMEGUARD_API_URI=http://localhost:8000`.
Could you merge?

2024-10-30 19:54 UTC, lightwalker-eth approved these changes
@Carbon225 @djstrong Awesome upgrades here! Approved 🚀

2024-10-30 19:56 UTC, merged