feat: [sc-25927] Update ENS Referral Program Landing Page for DevCon
namehash/namekit pull request #463
Opened 2024-11-08 20:31 UTC by eduramme

Story details: https://app.shortcut.com/ps-web3/story/25927

2024-11-08 20:34 UTC, eduramme commented on apps/namehashlabs.org/app/ens-referral-program/page.tsx
> +              buttonUrl="https://www.deform.cc/"
@lightwalker-eth just a heads-up that I added the link https://www.deform.cc/ here

2024-11-09 17:25 UTC, lightwalker-eth requested changes
@eduramme Hey thanks for the updates here. There's a few items to fix. Appreciate if you can fix these today. Thanks :+1:

2024-11-09 17:25 UTC, lightwalker-eth commented on apps/namehashlabs.org/data/ensProfiles.ts
> +      ensName: "duds.eth",
@eduramme Could you please set the avatar on your ENS profile?

![CleanShot 2024-11-09 at 21 09 21](https://github.com/user-attachments/assets/4bcc41ca-a7f7-4a1f-a551-4b55de31ec81)

I see you never set any avatar:

![CleanShot 2024-11-09 at 21 10 20](https://github.com/user-attachments/assets/8986ac93-7d8a-4097-9b5d-ee71911864c4)

2024-11-09 17:25 UTC, lightwalker-eth commented on apps/namehashlabs.org/components/1 - atoms/headline-banner.tsx
> +        <p className=" sm:pr-0">Meet us at DevCon in Bangkok 12-15 Nov 2024</p>
```suggestion
        <p className=" sm:pr-0">Meet us at DevCon in Bangkok 11-13 Nov 2024</p>
```

We'll be there only 11-13 :+1:

2024-11-09 17:25 UTC, lightwalker-eth commented on apps/namehashlabs.org/components/1 - atoms/headline-banner.tsx
>  export const HeadlineBanner = () => {
Please fix the height of the banner. It's too big.

![CleanShot 2024-11-09 at 21 13 42](https://github.com/user-attachments/assets/3655ffc8-3a5c-4d01-ad10-5693092ee2b5)

2024-11-11 01:13 UTC, lightwalker-eth approved these changes
@eduramme Hey looks great, thank you :+1:

2024-11-11 01:13 UTC, merged