Get log probability color
namehash/namekit pull request #512
Opened 2024-12-30 14:49 UTC by djstrong

2025-01-02 12:44 UTC, lightwalker-eth requested changes
@djstrong Hey great to see this!

@notrab Hey, could you please take the lead on the next steps for this PR? Thank you!

2025-01-02 12:44 UTC, lightwalker-eth commented on apps/namerank.io/app/indicator.tsx
> +  const getLogProbabilityColor = (val: number): [number, number, number] => {
@notrab Hey, could you please help to advance next steps here? The big picture is that this function is attempting to generate a RGB hex code that can be used to dynamically determine the color of an indicator based on a `log_probability` value. I asked @djstrong to focus on the math side of this logic so that we could then pass this goal off to you for refinement to align with TypeScript / Tailwind / CSS best practices. Please let us know if any questions!

@notrab Requested enhancements on this for you to lead include:
1. Rename the `val` param to something approximating `log_probability` to be more self documenting
2. Refine the return type to better align with best practices for how a color code might be returned.

2025-01-07 13:58 UTC, lightwalker-eth requested changes
@notrab Overall looks good! Just 1 change request

2025-01-07 13:58 UTC, lightwalker-eth commented on apps/namerank.io/app/indicator.tsx
> +  const width = Math.max(50, 128 * normalizedPercentage);
Lets define a named constant for 50 and 128 to make this code more self documenting. As I understand they represent min and max width of the indicator?

Suggest we make the min a bit less. Maybe only 20?

2025-01-07 14:01 UTC, notrab commented on apps/namerank.io/app/indicator.tsx
> +  const width = Math.max(50, 128 * normalizedPercentage);
Done!

2025-01-07 14:07 UTC, lightwalker-eth approved these changes
@notrab Thanks for update! Approved 🚀

2025-01-07 14:08 UTC, merged