feat: [sc-25972] Refine NameRank SDK
namehash/namekit pull request #515
Opened 2024-12-31 20:58 UTC by Carbon225

Story details: https://app.shortcut.com/ps-web3/story/25972

2025-01-02 13:02 UTC, lightwalker-eth requested changes
@Carbon225 Hey great to see the updates here. Reviewed in detail and shared feedback :+1: @djstrong FYI

2025-01-02 13:02 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +  /** The number of words in the label */
Can we please document more details about this `word_count` field? For example, is it sometimes 0 or undefined? What happens if we can't find any words? And when we do return a positive `word_count` value, how does this value relate to the `top_tokenization` field?

2025-01-02 13:02 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
>    tokenizations: Record<string, any>[];
Let's please also define an interface for the value of each of these records. We should avoid the use of `any`.

2025-01-03 21:57 UTC, djstrong commented on packages/namerank-sdk/src/index.ts
> +export enum CharacterType {
None of these are present in NameGuard SDK.

2025-01-03 23:03 UTC, djstrong commented
@lightwalker-eth I have addressed all issues.

2025-01-04 10:19 UTC, notrab commented
@djstrong @lightwalker-eth we should add a changesets entry so the types are released as a minor update.

2025-01-05 19:49 UTC, lightwalker-eth requested changes
@djstrong Hey super updates! Thank you. Reviewed and shared feedback :+1:

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
>     * const nameRankReport = await namerank.inspectName('vitalik.eth');
```suggestion
   * const nameRankResponse = await namerank.inspectName('vitalik.eth');
```

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +  /** The probability score for this tokenization, between 0 and 1 */
Suggest we reuse the more formal definition of `probability` from `NLPLabelAnalysis`.

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +  /** The natural log of the probability score, <= 0 */
Suggest we also update this to match `log_probability` in `NLPLabelAnalysis`.

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +  /** The result of the label inspection */
Could we also document here that `inspection` will be of type `InspectorResultNormalized` if `status` is `Normalized` and otherwise will be of type `InspectorResultUnnormalized`?

What if `status` is `Unknown`?

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +   * Must be greater than or equal to 0.
```suggestion
   * Always a non-negative integer.
```

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +   * The result of the NLP analysis on the label. If the label is not inspected, this field will be undefined.
Could we refine this to make it very explicit what it means for the label not to be inspected? What field / field value would define this case?

2025-01-05 19:49 UTC, lightwalker-eth commented on packages/namerank-sdk/src/index.ts
> +export enum CharacterType {
@djstrong Ah, I see. Am I correct to assume that these ideas are actually related to the LabelInspector? Assuming so, what do you think about creating a separate labelinspector.ts file that you could move those definitions into, and then importing those definitions back into this file.

My goal here is to keep this file more "pure" to NameRank.

I don't suggest we create a separate typescript package for a LabelInspector SDK in this PR. This would be a nice goal for a separate PR, where we might move this labelinspector.ts file into a separate package, but for now just creating a new and separate file in this current package is ok :+1:

Appreciate your advice!

2025-01-06 12:49 UTC, lightwalker-eth approved these changes
@djstrong Great updates! Reviewed and approved 🚀

2025-01-06 12:49 UTC, merged